<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Consultas</title>
  <meta name="viewport" content="width=device-width, initial-scale=1"><link rel='stylesheet'
  href='https://fonts.googleapis.com/css2?family=Rubik:wght@500&amp;display=swap'><link rel="stylesheet" href="app/view/css/home_style.css">
  <link rel="icon" href="https://www.iconpacks.net/icons/2/free-rocket-icon-3432-thumb.png">
</head>
<body>
<form method="POST" action="">
  <button type="submit" name="view" value="Pessoa">
    <span>Consultar!</span>
    <svg viewBox="-5 -5 110 110" preserveAspectRatio="none" aria-hidden="true">
      <path d="M0,0 C0,0 100,0 100,0 C100,0 100,100 100,100 C100,100 0,100 0,100 C0,100 0,0 0,0"/>
    </svg>
  </button>
</form>
  
</body>
</html>
